import { JobOpening } from '../../../../lib/types';

export const ALAMI_JOBS: JobOpening[] = [
  {
    company: 'ALAMI',
    departmentName: 'Engineering',
    description: '',
    employmentType: 'Full-time',
    url: 'https://jobs.lever.co/alamigroup/d02e11e9-b8a8-46e1-9e9f-82c7ec39e7ef',
    jobTitle: '[All Levels] QA Engineer - Remote Work',
    location: 'Jakarta',
  },
  {
    company: 'ALAMI',
    departmentName: 'Business Development',
    description: '',
    employmentType: 'Full-time',
    url: 'https://jobs.lever.co/alamigroup/a4557a27-512a-46bd-ad41-b59d952b7ee1',
    jobTitle: 'Business Development - Remote Working',
    location: 'Jakarta',
  },
  {
    company: 'ALAMI',
    departmentName: 'Business Development',
    description: '',
    employmentType: 'Full-time',
    url: 'https://jobs.lever.co/alamigroup/6200d9e3-923e-485c-892d-e4cbd1c7fc8a',
    jobTitle: 'Business Development Intern - Remote Working',
    location: 'Jakarta',
  },
  {
    company: 'ALAMI',
    departmentName: 'Business Development',
    description: '',
    employmentType: 'Full-time',
    url: 'https://jobs.lever.co/alamigroup/cbb443dd-c132-4752-968b-2b83537412a3',
    jobTitle:
      'Business Development Manager - Ecosystem Financing (Remote Working)',
    location: 'Jakarta',
  },
  {
    company: 'ALAMI',
    departmentName: 'Product Development',
    description: '',
    employmentType: 'Full-time',
    url: 'https://jobs.lever.co/alamigroup/8e687c86-0804-4323-8454-6463ca34fd9e',
    jobTitle: 'Business Intelligence Analyst Intern - Remote Working',
    location: 'Jakarta',
  },
  {
    company: 'ALAMI',
    departmentName: 'Product Development',
    description: '',
    employmentType: 'Full-time',
    url: 'https://jobs.lever.co/alamigroup/94a9707c-2674-4b33-93e4-541729809f3b',
    jobTitle: 'Data Engineer - Remote Work',
    location: 'Jakarta',
  },
  {
    company: 'ALAMI',
    departmentName: 'Engineering',
    description: '',
    employmentType: 'Full-time',
    url: 'https://jobs.lever.co/alamigroup/26e52b30-a382-4eb1-a60c-65254324563b',
    jobTitle: 'Information Security Engineer - Remote Work',
    location: 'Jakarta',
  },
  {
    company: 'ALAMI',
    departmentName: 'Operations',
    description: '',
    employmentType: 'Full-time',
    url: 'https://jobs.lever.co/alamigroup/d696fe9c-6f2b-413f-9801-3bb1dc2f619d',
    jobTitle: 'IT Application Support (In House) - Remote Work',
    location: 'Jakarta',
  },
  {
    company: 'ALAMI',
    departmentName: 'Operations',
    description: '',
    employmentType: 'Full-time',
    url: 'https://jobs.lever.co/alamigroup/cf4242dc-ab53-44d1-95d1-02ec0f46e491',
    jobTitle: 'Legal Digital Banking  - Remote Work',
    location: 'Jakarta',
  },
  {
    company: 'ALAMI',
    departmentName: 'Product Development',
    description: '',
    employmentType: 'Full-time',
    url: 'https://jobs.lever.co/alamigroup/7e70164b-d6a2-4567-a464-abefbe12ab80',
    jobTitle: 'Product Designer - Remote Work',
    location: 'Jakarta',
  },
  {
    company: 'ALAMI',
    departmentName: 'Product Development',
    description: '',
    employmentType: 'Full-time',
    url: 'https://jobs.lever.co/alamigroup/cf8fba63-404e-4844-a8f9-89094c8af2ab',
    jobTitle: 'Product Manager - Remote Work',
    location: 'Jakarta',
  },
  {
    company: 'ALAMI',
    departmentName: 'Engineering',
    description: '',
    employmentType: 'Full-time',
    url: 'https://jobs.lever.co/alamigroup/1e496258-db4d-445a-922e-0e448e22f7e9',
    jobTitle: 'Site Reliability Engineer (SRE)  - Remote Work',
    location: 'Jakarta',
  },
  {
    company: 'ALAMI',
    departmentName: 'Engineering',
    description: '',
    employmentType: 'Full-time',
    url: 'https://jobs.lever.co/alamigroup/962601ec-04e1-4057-913d-e5c832e6806f',
    jobTitle: 'Software Development Engineer in Test - Remote Work',
    location: 'Jakarta',
  },
  {
    company: 'ALAMI',
    departmentName: 'Corporate',
    description: '',
    employmentType: 'Full-time',
    url: 'https://jobs.lever.co/alamigroup/98d27fb8-8178-4cce-90da-604acba93f77',
    jobTitle: 'Sr. Tech Recruiter - Remote Work',
    location: 'Jakarta',
  },
  {
    company: 'ALAMI',
    departmentName: 'Corporate',
    description: '',
    employmentType: 'Full-time',
    url: 'https://jobs.lever.co/alamigroup/a6d88e83-5686-4d86-b2d5-dfff5952b38b',
    jobTitle: 'Talent Acquisition - Remote Work',
    location: 'Jakarta',
  },
];
