import { JobOpening } from '../../../../lib/types';

export const BukuWarung_JOBS: JobOpening[] = [
  {
    company: 'BukuWarung',
    departmentName: 'Engineering',
    description: '',
    employmentType: 'Full-time',
    url: 'https://jobs.lever.co/bukuwarung/a35f0085-f79a-411b-a955-b24739775000',
    jobTitle: 'Backend Engineer',
    location: 'Jakarta',
  },
  {
    company: 'BukuWarung',
    departmentName: 'Product, Design and Research',
    description: '',
    employmentType: 'Full-time',
    url: 'https://jobs.lever.co/bukuwarung/1a46c247-b1b4-46ce-8a02-67dcd4800a3b',
    jobTitle: 'Design Ops',
    location: 'Jakarta',
  },
  {
    company: 'BukuWarung',
    departmentName: 'Engineering',
    description: '',
    employmentType: 'Full-time',
    url: 'https://jobs.lever.co/bukuwarung/3ef5155b-c781-4d2a-85c1-59af018a944e',
    jobTitle: 'DevOps/SRE Engineer',
    location: 'Jakarta',
  },
  {
    company: 'BukuWarung',
    departmentName: 'Engineering',
    description: '',
    employmentType: 'Full-time',
    url: 'https://jobs.lever.co/bukuwarung/75b6c7db-58a7-45df-b266-095f83bf2221',
    jobTitle: 'Engineering Manager',
    location: 'Jakarta',
  },
  {
    company: 'BukuWarung',
    departmentName: 'Engineering',
    description: '',
    employmentType: 'Full-time',
    url: 'https://jobs.lever.co/bukuwarung/f04ab706-d8b8-42a2-b6f0-1a219cdf3ffc',
    jobTitle: 'Frontend Engineer',
    location: 'Jakarta',
  },
  {
    company: 'BukuWarung',
    departmentName: 'Product, Design and Research',
    description: '',
    employmentType: 'Full-time',
    url: 'https://jobs.lever.co/bukuwarung/04a9d008-d2df-4e08-b049-9eac025100e0',
    jobTitle: 'Internship: Administrative Intern',
    location: 'Jakarta',
  },
  {
    company: 'BukuWarung',
    departmentName: 'Product, Design and Research',
    description: '',
    employmentType: 'Full-time',
    url: 'https://jobs.lever.co/bukuwarung/45e07b64-0a5c-4779-a1c1-7ad2d72269e9',
    jobTitle: 'Lead  Product Manager',
    location: 'Jakarta',
  },
  {
    company: 'BukuWarung',
    departmentName: 'Engineering',
    description: '',
    employmentType: 'Full-time',
    url: 'https://jobs.lever.co/bukuwarung/ba39d131-80ad-4e06-8158-63fac294fe9a',
    jobTitle: 'Lead Frontend Engineer',
    location: 'Jakarta',
  },
  {
    company: 'BukuWarung',
    departmentName: 'Product, Design and Research',
    description: '',
    employmentType: 'Full-time',
    url: 'https://jobs.lever.co/bukuwarung/83d44b51-2b20-4447-b99f-43972083bb32',
    jobTitle: 'Lead Product Manager',
    location: 'Jakarta',
  },
  {
    company: 'BukuWarung',
    departmentName: 'Product, Design and Research',
    description: '',
    employmentType: 'Full-time',
    url: 'https://jobs.lever.co/bukuwarung/80b8087a-1ddd-42bb-a2bc-86bd28809dc7',
    jobTitle: 'Lead Product Manager - Platform',
    location: 'Jakarta',
  },
  {
    company: 'BukuWarung',
    departmentName: 'Product, Design and Research',
    description: '',
    employmentType: 'Full-time',
    url: 'https://jobs.lever.co/bukuwarung/bfc15cf6-3d45-408d-af1c-f02adef3cf83',
    jobTitle: 'Product Designer',
    location: 'Jakarta',
  },
  {
    company: 'BukuWarung',
    departmentName: 'Product, Design and Research',
    description: '',
    employmentType: 'Full-time',
    url: 'https://jobs.lever.co/bukuwarung/ef61445d-166c-4765-965c-58b72ee58da5',
    jobTitle: 'Product Designer Lead',
    location: 'Jakarta',
  },
  {
    company: 'BukuWarung',
    departmentName: 'Product, Design and Research',
    description: '',
    employmentType: 'Full-time',
    url: 'https://jobs.lever.co/bukuwarung/8d536617-7527-424e-ab03-9b1f437e7d64',
    jobTitle: 'Product Marketing Manager',
    location: 'Jakarta',
  },
  {
    company: 'BukuWarung',
    departmentName: 'Engineering',
    description: '',
    employmentType: 'Full-time',
    url: 'https://jobs.lever.co/bukuwarung/d28e0713-28e7-49bf-b630-39ea0759f206',
    jobTitle: 'QA Engineer',
    location: 'Jakarta',
  },
  {
    company: 'BukuWarung',
    departmentName: 'Engineering',
    description: '',
    employmentType: 'Full-time',
    url: 'https://jobs.lever.co/bukuwarung/af3156b2-69bc-41c0-b3ea-2a208281e5ea',
    jobTitle: 'Senior Backend Engineer',
    location: 'Jakarta',
  },
  {
    company: 'BukuWarung',
    departmentName: 'Engineering',
    description: '',
    employmentType: 'Full-time',
    url: 'https://jobs.lever.co/bukuwarung/32f42416-abdf-4754-94ee-a560ba84a809',
    jobTitle: 'Senior Frontend Engineer',
    location: 'Jakarta',
  },
  {
    company: 'BukuWarung',
    departmentName: 'Product, Design and Research',
    description: '',
    employmentType: 'Full-time',
    url: 'https://jobs.lever.co/bukuwarung/2af7975a-26f0-4c63-b5b4-13edb9d78577',
    jobTitle: 'Senior Product Manager',
    location: 'Jakarta',
  },
  {
    company: 'BukuWarung',
    departmentName: 'Product, Design and Research',
    description: '',
    employmentType: 'Full-time',
    url: 'https://jobs.lever.co/bukuwarung/3624e36b-6297-4f83-8eae-6b62073e6532',
    jobTitle: 'Senior Product Manager',
    location: 'Jakarta',
  },
  {
    company: 'BukuWarung',
    departmentName: 'Product, Design and Research',
    description: '',
    employmentType: 'Full-time',
    url: 'https://jobs.lever.co/bukuwarung/9ec038fc-d4c1-4794-9991-570f4710342a',
    jobTitle: 'Senior Product Manager - Platform',
    location: 'Jakarta',
  },
  {
    company: 'BukuWarung',
    departmentName: 'Engineering',
    description: '',
    employmentType: 'Full-time',
    url: 'https://jobs.lever.co/bukuwarung/54e67639-8473-41e7-a0b8-1b8ff3da8a52',
    jobTitle: 'Senior QA Engineer',
    location: 'Jakarta',
  },
  {
    company: 'BukuWarung',
    departmentName: 'Engineering',
    description: '',
    employmentType: 'Full-time',
    url: 'https://jobs.lever.co/bukuwarung/b737ea34-ab46-4323-9dd3-54d72fbcfe02',
    jobTitle: 'Senior QA Engineer',
    location: 'Jakarta',
  },
  {
    company: 'BukuWarung',
    departmentName: 'Product, Design and Research',
    description: '',
    employmentType: 'Full-time',
    url: 'https://jobs.lever.co/bukuwarung/2cdbde87-43ac-449a-aed6-c434bc371794',
    jobTitle: 'UX Research Lead',
    location: 'Jakarta',
  },
  {
    company: 'BukuWarung',
    departmentName: 'Product, Design and Research',
    description: '',
    employmentType: 'Full-time',
    url: 'https://jobs.lever.co/bukuwarung/3343b969-43cd-4350-860a-4ec74e4ea10b',
    jobTitle: 'UX Research Ops',
    location: 'Jakarta',
  },
  {
    company: 'BukuWarung',
    departmentName: 'Product, Design and Research',
    description: '',
    employmentType: 'Full-time',
    url: 'https://jobs.lever.co/bukuwarung/58825111-17ba-4210-8056-452ca2c00ea7',
    jobTitle: 'UX Researcher',
    location: 'Jakarta',
  },
];
