import { JobOpening } from '../../../../lib/types';

export const CoLearn_JOBS: JobOpening[] = [
  {
    company: 'CoLearn',
    departmentName: 'Design & User Experience',
    description: '',
    url: 'https://boards.greenhouse.io//colearn/jobs/4683111003',
    jobTitle: 'Product Researcher',
    location: '',
  },
  {
    company: 'CoLearn',
    departmentName: 'Engineering',
    description: '',
    url: 'https://boards.greenhouse.io//colearn/jobs/4700767003',
    jobTitle: 'Product Engineer, Android',
    location: '',
  },
  {
    company: 'CoLearn',
    departmentName: 'Engineering',
    description: '',
    url: 'https://boards.greenhouse.io//colearn/jobs/4698863003',
    jobTitle: 'Product Engineer, iOS',
    location: '',
  },
  {
    company: 'CoLearn',
    departmentName: 'Live Streaming',
    description: '',
    url: 'https://boards.greenhouse.io//colearn/jobs/4996782003',
    jobTitle: 'Akademi Guru Juara',
    location: '',
  },
  {
    company: 'CoLearn',
    departmentName: 'Live Streaming',
    description: '',
    url: 'https://boards.greenhouse.io//colearn/jobs/4931947003',
    jobTitle: 'Knowledge Management Specialist',
    location: '',
  },
  {
    company: 'CoLearn',
    departmentName: 'Live Streaming',
    description: '',
    url: 'https://boards.greenhouse.io//colearn/jobs/4931922003',
    jobTitle: 'Live Experiment Lead',
    location: '',
  },
  {
    company: 'CoLearn',
    departmentName: 'Live Streaming',
    description: '',
    url: 'https://boards.greenhouse.io//colearn/jobs/5032816003',
    jobTitle: 'Live Streaming Associate',
    location: '',
  },
  {
    company: 'CoLearn',
    departmentName: 'Live Streaming',
    description: '',
    url: 'https://boards.greenhouse.io//colearn/jobs/5061662003',
    jobTitle: 'Student Engagement Intern',
    location: '',
  },
  {
    company: 'CoLearn',
    departmentName: 'Sales',
    description: '',
    url: 'https://boards.greenhouse.io//colearn/jobs/4914435003',
    jobTitle: 'Academic Sales Executive',
    location: '',
  },
  {
    company: 'CoLearn',
    departmentName: 'Sales',
    description: '',
    url: 'https://boards.greenhouse.io//colearn/jobs/4956464003',
    jobTitle: 'Sales Community Lead',
    location: '',
  },
  {
    company: 'CoLearn',
    departmentName: 'Sales',
    description: '',
    url: 'https://boards.greenhouse.io//colearn/jobs/4914436003',
    jobTitle: 'Sales Director',
    location: '',
  },
  {
    company: 'CoLearn',
    departmentName: 'Sales',
    description: '',
    url: 'https://boards.greenhouse.io//colearn/jobs/5002373003',
    jobTitle: 'Sales Manager',
    location: '',
  },
  {
    company: 'CoLearn',
    departmentName: 'Sales',
    description: '',
    url: 'https://boards.greenhouse.io//colearn/jobs/5008082003',
    jobTitle: 'Sales Supervisor',
    location: '',
  },
];
