import { JobOpening } from '../../../../lib/types';

export const eFishery_JOBS: JobOpening[] = [
  {
    company: 'eFishery',
    departmentName: 'Technology & Data',
    description: '',
    employmentType: 'Contract',
    url: 'https://efishery.com/en/job/data-governance/',
    jobTitle: 'Data Governance',
    location: '',
  },
  {
    company: 'eFishery',
    departmentName: 'Technology & Data',
    description: '',
    employmentType: 'Contract',
    url: 'https://efishery.com/en/job/backend-engineer/',
    jobTitle: 'Backend Engineer',
    location: '',
  },
  {
    company: 'eFishery',
    departmentName: 'Technology & Data',
    description: '',
    employmentType: 'Contract',
    url: 'https://efishery.com/en/job/data-engineer/',
    jobTitle: 'Data Engineer',
    location: '',
  },
  {
    company: 'eFishery',
    departmentName: 'Technology & Data',
    description: '',
    employmentType: 'Contract',
    url: 'https://efishery.com/en/job/data-science-manager/',
    jobTitle: 'Data Science Manager',
    location: '',
  },
  {
    company: 'eFishery',
    departmentName: 'Technology & Data',
    description: '',
    employmentType: 'Contract',
    url: 'https://efishery.com/en/job/core-tech-manager/',
    jobTitle: 'Core Tech Manager',
    location: '',
  },
  {
    company: 'eFishery',
    departmentName: 'Technology & Data',
    description: '',
    employmentType: 'Contract',
    url: 'https://efishery.com/en/job/iot-engineer-product/',
    jobTitle: 'IoT Engineer Product',
    location: '',
  },
  {
    company: 'eFishery',
    departmentName: 'Technology & Data',
    description: '',
    employmentType: 'Contract',
    url: 'https://efishery.com/en/job/product-data-analyst-2/',
    jobTitle: 'Product Data Analyst',
    location: '',
  },
  {
    company: 'eFishery',
    departmentName: 'Technology & Data',
    description: '',
    employmentType: 'Contract',
    url: 'https://efishery.com/en/job/business-data-analyst-2/',
    jobTitle: 'Business Data Analyst',
    location: '',
  },
  {
    company: 'eFishery',
    departmentName: 'Technology & Data',
    description: '',
    employmentType: 'Contract',
    url: 'https://efishery.com/en/job/software-engineer-product-frontend/',
    jobTitle: 'Software Engineer Product (Frontend)',
    location: '',
  },
  {
    company: 'eFishery',
    departmentName: 'Technology & Data',
    description: '',
    employmentType: 'Contract',
    url: 'https://efishery.com/en/job/software-engineer-product-backend/',
    jobTitle: 'Software Engineer Product (Backend)',
    location: '',
  },
  {
    company: 'eFishery',
    departmentName: 'Technology & Data',
    description: '',
    employmentType: 'Contract',
    url: 'https://efishery.com/en/job/data-governance-2/',
    jobTitle: 'Data Governance',
    location: '',
  },
  {
    company: 'eFishery',
    departmentName: 'Technology & Data',
    description: '',
    employmentType: 'Contract',
    url: 'https://efishery.com/en/job/qa-engineer-2/',
    jobTitle: 'QA Engineer',
    location: '',
  },
  {
    company: 'eFishery',
    departmentName: 'Technology & Data',
    description: '',
    employmentType: 'Contract',
    url: 'https://efishery.com/en/job/fullstack-software-engineer/',
    jobTitle: 'Fullstack Software Engineer',
    location: '',
  },
  {
    company: 'eFishery',
    departmentName: 'Technology & Data',
    description: '',
    employmentType: 'Contract',
    url: 'https://efishery.com/en/job/platform-software-engineer/',
    jobTitle: 'Platform Software Engineer',
    location: '',
  },
  {
    company: 'eFishery',
    departmentName: 'Technology & Data',
    description: '',
    employmentType: 'Contract',
    url: 'https://efishery.com/en/job/interaction-designer-2/',
    jobTitle: 'Interaction Designer',
    location: '',
  },
];
