import { JobOpening } from '../../../../lib/types';

export const Finantier_JOBS: JobOpening[] = [
  {
    company: 'Finantier',
    departmentName: 'Growth',
    description: '',
    employmentType: 'Full-time',
    url: 'https://jobs.lever.co/Finantier/a6250dba-9ade-4794-b692-7075a5a716fd',
    jobTitle: 'Business Development Internship',
    location: 'Remote',
  },
  {
    company: 'Finantier',
    departmentName: 'Growth',
    description: '',
    employmentType: 'Full-time',
    url: 'https://jobs.lever.co/Finantier/6b49d009-db75-453e-add3-d6b5e2524de7',
    jobTitle: 'Business Development Manager',
    location: 'Remote',
  },
  {
    company: 'Finantier',
    departmentName: 'Operations',
    description: '',
    employmentType: 'Full-time',
    url: 'https://jobs.lever.co/Finantier/ccbfe652-7367-492a-8563-4e987d70dfcb',
    jobTitle: 'Indonesia - Legal',
    location: 'Remote',
  },
  {
    company: 'Finantier',
    departmentName: 'Technology',
    description: '',
    employmentType: 'Full-time',
    url: 'https://jobs.lever.co/Finantier/e19e199e-1ec3-4c80-aca8-ddbe4cfb81a8',
    jobTitle: 'Indonesia Backend Engineer',
    location: 'Remote',
  },
  {
    company: 'Finantier',
    departmentName: 'Technology',
    description: '',
    employmentType: 'Full-time',
    url: 'https://jobs.lever.co/Finantier/92e41ff2-2c83-4c2c-8f74-c5091c2a63cc',
    jobTitle: 'Indonesia Data Analyst',
    location: 'Remote',
  },
  {
    company: 'Finantier',
    departmentName: 'Technology',
    description: '',
    employmentType: 'Full-time',
    url: 'https://jobs.lever.co/Finantier/551917ce-444e-406c-92a3-75dd659afb94',
    jobTitle: 'Indonesia Data Engineer',
    location: 'Remote',
  },
  {
    company: 'Finantier',
    departmentName: 'Technology',
    description: '',
    employmentType: 'Full-time',
    url: 'https://jobs.lever.co/Finantier/d20ecb02-9260-43d5-b6ef-3e5e2833b305',
    jobTitle: 'Indonesia Data Scientist',
    location: 'Remote',
  },
  {
    company: 'Finantier',
    departmentName: 'Technology',
    description: '',
    employmentType: 'Full-time',
    url: 'https://jobs.lever.co/Finantier/2551c81e-818a-4521-8f7a-749f9f095c34',
    jobTitle: 'Indonesia Engineering Manager',
    location: 'Remote',
  },
  {
    company: 'Finantier',
    departmentName: 'Technology',
    description: '',
    employmentType: 'Full-time',
    url: 'https://jobs.lever.co/Finantier/97ab4e69-a936-46cf-aa7a-e9acd3dd0ff4',
    jobTitle: 'Indonesia Frontend Engineer',
    location: 'Remote',
  },
  {
    company: 'Finantier',
    departmentName: 'Product',
    description: '',
    employmentType: 'Full-time',
    url: 'https://jobs.lever.co/Finantier/8e099a4b-b9b0-472e-8d0e-f2edc580a10b',
    jobTitle: 'Indonesia Product Manager',
    location: 'Remote',
  },
  {
    company: 'Finantier',
    departmentName: 'Risk Manager',
    description: '',
    employmentType: 'Full-time',
    url: 'https://jobs.lever.co/Finantier/02e9b5c3-7b10-416c-84f7-3bc60cc2510e',
    jobTitle: 'Indonesia Risk Manager',
    location: 'Remote',
  },
  {
    company: 'Finantier',
    departmentName: 'Technology',
    description: '',
    employmentType: 'Full-time',
    url: 'https://jobs.lever.co/Finantier/66d409be-33be-4851-8fed-cbc71b701031',
    jobTitle: 'Indonesia Senior Backend Engineer',
    location: 'Remote',
  },
  {
    company: 'Finantier',
    departmentName: 'Technology',
    description: '',
    employmentType: 'Full-time',
    url: 'https://jobs.lever.co/Finantier/23f62aec-cdab-48f4-b2bc-0c8e611c6452',
    jobTitle: 'Indonesia Senior DevOps Engineer',
    location: 'Remote',
  },
  {
    company: 'Finantier',
    departmentName: 'Technology',
    description: '',
    employmentType: 'Full-time',
    url: 'https://jobs.lever.co/Finantier/5f72b9be-5c5f-4ec1-a4f9-0f9cf9ca1d47',
    jobTitle: 'Indonesia Senior Frontend Engineer',
    location: 'Remote',
  },
  {
    company: 'Finantier',
    departmentName: 'Technology',
    description: '',
    employmentType: 'Full-time',
    url: 'https://jobs.lever.co/Finantier/f9b2b645-5905-4b49-b4c9-2c1c389b289b',
    jobTitle: 'Indonesia Senior Machine Learning Engineer',
    location: 'Remote',
  },
  {
    company: 'Finantier',
    departmentName: 'Technology',
    description: '',
    employmentType: 'Full-time',
    url: 'https://jobs.lever.co/Finantier/b968d1e7-c8c5-4639-b344-ca25118e9970',
    jobTitle: 'Indonesia Senior Quality Engineer',
    location: 'Remote',
  },
  {
    company: 'Finantier',
    departmentName: 'Technology',
    description: '',
    employmentType: 'Full-time',
    url: 'https://jobs.lever.co/Finantier/282f8216-2330-4994-8025-cf6768cc8dca',
    jobTitle: 'Indonesia Technical Lead',
    location: 'Remote',
  },
  {
    company: 'Finantier',
    departmentName: 'Product',
    description: '',
    employmentType: 'Full-time',
    url: 'https://jobs.lever.co/Finantier/b586a3e3-0af0-4eb5-b397-47e04d980591',
    jobTitle: 'Indonesia UI/UX Product Designer',
    location: 'Remote',
  },
  {
    company: 'Finantier',
    departmentName: 'Growth',
    description: '',
    employmentType: 'Full-time',
    url: 'https://jobs.lever.co/Finantier/be534d88-7a31-45a9-b98a-dc6df37a7071',
    jobTitle: 'Junior Business Development Manager',
    location: 'Remote',
  },
  {
    company: 'Finantier',
    departmentName: 'Technology',
    description: '',
    employmentType: 'Full-time',
    url: 'https://jobs.lever.co/Finantier/67593423-43d4-465b-a899-f9ca1fb30562',
    jobTitle: 'Junior Defensive Engineer (Blue Team)',
    location: 'Remote',
  },
  {
    company: 'Finantier',
    departmentName: 'Technology',
    description: '',
    employmentType: 'Full-time',
    url: 'https://jobs.lever.co/Finantier/2bad4207-9a3e-42dc-b116-276b1973005d',
    jobTitle: 'Junior Security Offensive (Red Team)',
    location: 'Remote',
  },
  {
    company: 'Finantier',
    departmentName: 'Growth',
    description: '',
    employmentType: 'Full-time',
    url: 'https://jobs.lever.co/Finantier/ef4819f8-eed0-4afe-9091-a2fae11c14b4',
    jobTitle: 'Performance Marketing',
    location: 'Remote',
  },
  {
    company: 'Finantier',
    departmentName: 'Growth',
    description: '',
    employmentType: 'Full-time',
    url: 'https://jobs.lever.co/Finantier/b5c0429a-a5ec-4de4-8c2f-dc991590efed',
    jobTitle: 'Philippines Marketing Lead',
    location: 'Remote',
  },
  {
    company: 'Finantier',
    departmentName: 'Product',
    description: '',
    employmentType: 'Full-time',
    url: 'https://jobs.lever.co/Finantier/1cc2d37b-49d8-4d58-8659-198644563356',
    jobTitle: 'Philippines Product Manager',
    location: 'Remote',
  },
  {
    company: 'Finantier',
    departmentName: 'Product',
    description: '',
    employmentType: 'Full-time',
    url: 'https://jobs.lever.co/Finantier/2fa9958b-7966-4865-bb34-b38afdb1b457',
    jobTitle: 'Product Internship',
    location: 'Remote',
  },
  {
    company: 'Finantier',
    departmentName: 'People',
    description: '',
    employmentType: 'Full-time',
    url: 'https://jobs.lever.co/Finantier/65934766-9073-4ecb-9e84-8707674d524c',
    jobTitle: 'SEA Talent Acquisition',
    location: 'Remote',
  },
  {
    company: 'Finantier',
    departmentName: 'Technology',
    description: '',
    employmentType: 'Full-time',
    url: 'https://jobs.lever.co/Finantier/00468b2a-492b-432b-b6a1-23561ac7296c',
    jobTitle: 'Senior Defensive Engineer (Blue Team)',
    location: 'Remote',
  },
  {
    company: 'Finantier',
    departmentName: 'Technology',
    description: '',
    employmentType: 'Full-time',
    url: 'https://jobs.lever.co/Finantier/ea241dac-512d-4bdf-8dae-3d58034baa04',
    jobTitle: 'Senior Security Offensive (Red Team)',
    location: 'Remote',
  },
  {
    company: 'Finantier',
    departmentName: 'Technology',
    description: '',
    employmentType: 'Full-time',
    url: 'https://jobs.lever.co/Finantier/f62944ea-bf8e-42d7-bd56-9066a553e579',
    jobTitle: 'Software Engineering Internship',
    location: 'Remote',
  },
];
