import { JobOpening } from '../../../../lib/types';

export const FlipId_JOBS: JobOpening[] = [
  {
    company: 'Flip.id',
    departmentName: 'Marketing',
    description: '',
    employmentType: 'Full-time',
    url: 'https://career.flip.id/jobs/6onnySvp2jCp/corporate-communication-intern-paid-internship-remote',
    jobTitle: 'Corporate Communication Intern (Paid Internship) (Remote)',
    location: 'Remote',
  },
  {
    company: 'Flip.id',
    departmentName: 'Marketing',
    description: '',
    employmentType: 'Full-time',
    url: 'https://career.flip.id/jobs/T8gETD6T3ldm/crm-and-promo-specialist-remote',
    jobTitle: 'CRM and Promo Specialist (Remote)',
    location: 'Remote',
  },
  {
    company: 'Flip.id',
    departmentName: 'Marketing',
    description: '',
    employmentType: 'Full-time',
    url: 'https://career.flip.id/jobs/yvUC2Obpv1tD/product-marketing-manager-remote',
    jobTitle: 'Product Marketing Manager (Remote)',
    location: 'Remote',
  },
  {
    company: 'Flip.id',
    departmentName: 'Marketing',
    description: '',
    employmentType: 'Full-time',
    url: 'https://career.flip.id/jobs/RvkUtHTwRK69/research-associate-remote',
    jobTitle: 'Research Associate (Remote)',
    location: 'Remote',
  },
  {
    company: 'Flip.id',
    departmentName: 'Finance',
    description: '',
    employmentType: 'Full-time',
    url: 'https://career.flip.id/jobs/1QNDSQqUieQz/cost-control-budget-manager-remote',
    jobTitle: 'Cost Control & Budget Manager (Remote)',
    location: 'Remote',
  },
  {
    company: 'Flip.id',
    departmentName: 'Finance',
    description: '',
    employmentType: 'Full-time',
    url: 'https://career.flip.id/jobs/TlpwY-IVwYx_/treasury-fund-manager-remote',
    jobTitle: 'Treasury Fund Manager (Remote)',
    location: 'Remote',
  },
  {
    company: 'Flip.id',
    departmentName: 'Finance',
    description: '',
    employmentType: 'Full-time',
    url: 'https://career.flip.id/jobs/Ddxq7Nw_k8PN/treasury-officer-remote',
    jobTitle: 'Treasury Officer (Remote)',
    location: 'Remote',
  },
  {
    company: 'Flip.id',
    departmentName: 'B2B Solution',
    description: '',
    employmentType: 'Full-time',
    url: 'https://career.flip.id/jobs/LfAOSECkiI4v/b2b-consultant',
    jobTitle: 'B2B Consultant',
    location: 'Remote',
  },
  {
    company: 'Flip.id',
    departmentName: 'Human Resources',
    description: '',
    employmentType: 'Full-time',
    url: 'https://career.flip.id/jobs/C6aZAnU80EqH/employer-branding-intern-remote',
    jobTitle: 'Employer Branding Intern (Remote)',
    location: 'Remote',
  },
  {
    company: 'Flip.id',
    departmentName: 'Human Resources',
    description: '',
    employmentType: 'Full-time',
    url: 'https://career.flip.id/jobs/v6VtqU7ZeTk5/hr-development-intern-remote',
    jobTitle: 'HR Development Intern (Remote)',
    location: 'Remote',
  },
  {
    company: 'Flip.id',
    departmentName: 'Human Resources',
    description: '',
    employmentType: 'Full-time',
    url: 'https://career.flip.id/jobs/rNkGAE_nL7Oh/it-support-intern-paid-internship',
    jobTitle: 'IT Support Intern (Paid Internship)',
    location: 'Remote',
  },
  {
    company: 'Flip.id',
    departmentName: 'Human Resources',
    description: '',
    employmentType: 'Full-time',
    url: 'https://career.flip.id/jobs/fWVGY7ctJrGp/learning-and-development-specialist-remote',
    jobTitle: 'Learning and Development Specialist (Remote)',
    location: 'Remote',
  },
  {
    company: 'Flip.id',
    departmentName: 'Human Resources',
    description: '',
    employmentType: 'Full-time',
    url: 'https://career.flip.id/jobs/Wyrgr6Ju76z2/people-business-partner-tech-remote',
    jobTitle: 'People Business Partner - Tech (Remote)',
    location: 'Remote',
  },
  {
    company: 'Flip.id',
    departmentName: 'Human Resources',
    description: '',
    employmentType: 'Full-time',
    url: 'https://career.flip.id/jobs/0_tJf7IQr-Az/technical-recruiter-india-remote',
    jobTitle: 'Technical Recruiter (India) (Remote)',
    location: 'Remote',
  },
  {
    company: 'Flip.id',
    departmentName: 'Human Resources',
    description: '',
    employmentType: 'Full-time',
    url: 'https://career.flip.id/jobs/-o1Njo23jqip/technical-recruiter-remote',
    jobTitle: 'Technical Recruiter (Remote)',
    location: 'Remote',
  },
  {
    company: 'Flip.id',
    departmentName: 'Design',
    description: '',
    employmentType: 'Full-time',
    url: 'https://career.flip.id/jobs/s9x1Imjrtq3N/product-design-lead-remote',
    jobTitle: 'Product Design Lead (Remote)',
    location: 'Remote',
  },
  {
    company: 'Flip.id',
    departmentName: 'Product',
    description: '',
    employmentType: 'Full-time',
    url: 'https://career.flip.id/jobs/N3_q7lPOo6CR/lead-product-manager-consumer-solutions-remote',
    jobTitle: 'Lead Product Manager Consumer Solutions (Remote)',
    location: 'Remote',
  },
  {
    company: 'Flip.id',
    departmentName: 'Product',
    description: '',
    employmentType: 'Full-time',
    url: 'https://career.flip.id/jobs/9bjMRua1iWNR/senior-product-manager-consumer-app-platform-remote',
    jobTitle: 'Senior Product Manager - Consumer App Platform (Remote)',
    location: 'Remote',
  },
  {
    company: 'Flip.id',
    departmentName: 'Product',
    description: '',
    employmentType: 'Full-time',
    url: 'https://career.flip.id/jobs/xrpmQYGTPnVS/senior-product-manager-digital-products-remote',
    jobTitle: 'Senior Product Manager - Digital Products (Remote)',
    location: 'Remote',
  },
  {
    company: 'Flip.id',
    departmentName: 'Product',
    description: '',
    employmentType: 'Full-time',
    url: 'https://career.flip.id/jobs/UQ_Yf3SeYbBo/senior-product-manager-platform-and-internal-products-remote',
    jobTitle:
      'Senior Product Manager - Platform and Internal Products (Remote)',
    location: 'Remote',
  },
  {
    company: 'Flip.id',
    departmentName: 'Data',
    description: '',
    employmentType: 'Full-time',
    url: 'https://career.flip.id/jobs/w7mOxQv2jswr/data-analyst-remote',
    jobTitle: 'Data Analyst (Remote)',
    location: 'Remote',
  },
  {
    company: 'Flip.id',
    departmentName: 'Legal',
    description: '',
    employmentType: 'Full-time',
    url: 'https://career.flip.id/jobs/kZdr8k8fbrH_/compliance-specialist-remote',
    jobTitle: 'Compliance Specialist (Remote)',
    location: 'Remote',
  },
  {
    company: 'Flip.id',
    departmentName: 'Engineering',
    description: '',
    employmentType: 'Full-time',
    url: 'https://career.flip.id/jobs/av5DNNgLRmY5/senior-site-reliability-engineer-remote',
    jobTitle: 'Senior Site Reliability Engineer (Remote)',
    location: 'Remote',
  },
  {
    company: 'Flip.id',
    departmentName: 'Engineering',
    description: '',
    employmentType: 'Full-time',
    url: 'https://career.flip.id/jobs/5NSAAaA50HOO/senior-software-engineer-frontend-remote',
    jobTitle: 'Senior Software Engineer (Frontend) (Remote)',
    location: 'Remote',
  },
  {
    company: 'Flip.id',
    departmentName: 'Engineering',
    description: '',
    employmentType: 'Full-time',
    url: 'https://career.flip.id/jobs/FiYMEnZxqDVo/senior-software-engineer-mobile-react-native',
    jobTitle: 'Senior Software Engineer (Mobile - React Native)',
    location: 'Remote',
  },
  {
    company: 'Flip.id',
    departmentName: 'Engineering',
    description: '',
    employmentType: 'Full-time',
    url: 'https://career.flip.id/jobs/L7D22cHGbWrl/senior-software-engineer-backend-remote',
    jobTitle: 'Senior Software Engineer - Backend (Remote)',
    location: 'Remote',
  },
  {
    company: 'Flip.id',
    departmentName: 'Engineering',
    description: '',
    employmentType: 'Full-time',
    url: 'https://career.flip.id/jobs/aCAhYB-2zC5O/senior-test-engineer-remote',
    jobTitle: 'Senior Test Engineer (Remote)',
    location: 'Remote',
  },
  {
    company: 'Flip.id',
    departmentName: 'Engineering',
    description: '',
    employmentType: 'Full-time',
    url: 'https://career.flip.id/jobs/z0Y1S_pSaxcR/site-reliability-engineer-manager-remote',
    jobTitle: 'Site Reliability Engineer Manager (Remote)',
    location: 'Remote',
  },
  {
    company: 'Flip.id',
    departmentName: 'Engineering',
    description: '',
    employmentType: 'Full-time',
    url: 'https://career.flip.id/jobs/O5_Vhw5QYasW/software-engineer-backend-remote',
    jobTitle: 'Software Engineer (Backend) (Remote)',
    location: 'Remote',
  },
  {
    company: 'Flip.id',
    departmentName: 'Engineering',
    description: '',
    employmentType: 'Full-time',
    url: 'https://career.flip.id/jobs/n1yTFSGWuYgX/software-engineer-frontend',
    jobTitle: 'Software Engineer (Frontend)',
    location: 'Remote',
  },
  {
    company: 'Flip.id',
    departmentName: 'Engineering',
    description: '',
    employmentType: 'Full-time',
    url: 'https://career.flip.id/jobs/5qsLnCWsc6m4/software-engineer-mobile-react-native-remote',
    jobTitle: 'Software Engineer (Mobile - React Native) (Remote)',
    location: 'Remote',
  },
  {
    company: 'Flip.id',
    departmentName: 'Engineering',
    description: '',
    employmentType: 'Full-time',
    url: 'https://career.flip.id/jobs/3U-OhS24hJJx/staff-software-engineer-backend-remote',
    jobTitle: 'Staff Software Engineer (Backend) (Remote)',
    location: 'Remote',
  },
  {
    company: 'Flip.id',
    departmentName: 'Engineering',
    description: '',
    employmentType: 'Full-time',
    url: 'https://career.flip.id/jobs/-MIOY_yvgm6y/test-engineer-remote',
    jobTitle: 'Test Engineer (Remote)',
    location: 'Remote',
  },
  {
    company: 'Flip.id',
    departmentName: 'Management',
    description: '',
    employmentType: 'Full-time',
    url: 'https://career.flip.id/jobs/dQLxKTP2pm7O/government-relation-lead-remote',
    jobTitle: 'Government Relation Lead (Remote)',
    location: 'Remote',
  },
  {
    company: 'Flip.id',
    departmentName: 'Business Development',
    description: '',
    employmentType: 'Full-time',
    url: 'https://career.flip.id/jobs/AnDxgPvzcKAr/head-of-business-development-partnership-remote',
    jobTitle: 'Head of Business Development Partnership (Remote)',
    location: 'Remote',
  },
  {
    company: 'Flip.id',
    departmentName: 'Office Operation',
    description: '',
    employmentType: 'Full-time',
    url: 'https://career.flip.id/jobs/2s0SQveakYM3/fraud-manager-remote',
    jobTitle: 'Fraud Manager (Remote)',
    location: 'Remote',
  },
  {
    company: 'Flip.id',
    departmentName: 'Office Operation',
    description: '',
    employmentType: 'Full-time',
    url: 'https://career.flip.id/jobs/gTH7zRmxv6TP/head-of-fraud-management-remote',
    jobTitle: 'Head of Fraud Management (Remote)',
    location: 'Remote',
  },
  {
    company: 'Flip.id',
    departmentName: 'Procurement',
    description: '',
    employmentType: 'Full-time',
    url: 'https://career.flip.id/jobs/QgEajm_jt20Q/procurement-business-partner-and-operation-remote',
    jobTitle: 'Procurement Business Partner and Operation (Remote)',
    location: 'Remote',
  },
  {
    company: 'Flip.id',
    departmentName: 'Procurement',
    description: '',
    employmentType: 'Full-time',
    url: 'https://career.flip.id/jobs/YoP_oAjJ8X_w/procurement-sourcing-associate-remote',
    jobTitle: 'Procurement Sourcing Associate (Remote)',
    location: 'Remote',
  },
];
