import { JobOpening } from '../../../../lib/types';

export const Moladin_JOBS: JobOpening[] = [
  {
    company: 'Moladin',
    departmentName: 'Technology',
    description: '',
    url: 'https://moladin.com/careers/2-Engineering-Manager-II',
    jobTitle: 'Engineering Manager II',
    location: 'Remote',
    publishedAt: '2022-02-05T03:53:51.000Z',
  },
  {
    company: 'Moladin',
    departmentName: 'Technology',
    description: '',
    url: 'https://moladin.com/careers/3-Sr-Software-Engineer---Backend',
    jobTitle: 'Sr Software Engineer - Backend',
    location: 'Remote',
    publishedAt: '2022-02-07T04:06:06.000Z',
  },
  {
    company: 'Moladin',
    departmentName: 'Technology',
    description: '',
    url: 'https://moladin.com/careers/4-Sr-Software-Engineer---Frontend',
    jobTitle: 'Sr Software Engineer - Frontend',
    location: 'Remote',
    publishedAt: '2022-02-07T04:17:13.000Z',
  },
  {
    company: 'Moladin',
    departmentName: 'Technology',
    description: '',
    url: 'https://moladin.com/careers/5-Technical-Architect---Frontend',
    jobTitle: 'Technical Architect - Frontend',
    location: 'Remote',
    publishedAt: '2022-02-07T04:34:53.000Z',
  },
  {
    company: 'Moladin',
    departmentName: 'Technology',
    description: '',
    url: 'https://moladin.com/careers/6-Technical-Architect---Android',
    jobTitle: 'Technical Architect - Android',
    location: 'Remote',
    publishedAt: '2022-02-07T04:59:27.000Z',
  },
  {
    company: 'Moladin',
    departmentName: 'Technology',
    description: '',
    url: 'https://moladin.com/careers/7-Software-Engineer---Backend',
    jobTitle: 'Software Engineer - Backend',
    location: 'Remote',
    publishedAt: '2022-02-07T18:07:21.000Z',
  },
  {
    company: 'Moladin',
    departmentName: 'Technology',
    description: '',
    url: 'https://moladin.com/careers/8-Software-Engineer---Backend',
    jobTitle: 'Software Engineer - Backend',
    location: 'Remote',
    publishedAt: '2022-02-07T18:07:21.000Z',
  },
  {
    company: 'Moladin',
    departmentName: 'Product',
    description: '',
    url: 'https://moladin.com/careers/9-Associate-Product-Manager',
    jobTitle: 'Associate Product Manager',
    location: 'Remote',
    publishedAt: '2022-02-07T23:27:30.000Z',
  },
  {
    company: 'Moladin',
    departmentName: 'Technology',
    description: '',
    url: 'https://moladin.com/careers/12-DevOps-Engineer',
    jobTitle: 'DevOps Engineer',
    location: 'Remote',
    publishedAt: '2022-02-08T08:58:56.000Z',
  },
  {
    company: 'Moladin',
    departmentName: 'Technology',
    description: '',
    url: 'https://moladin.com/careers/13-DevOps-Engineer',
    jobTitle: 'DevOps Engineer',
    location: 'Remote',
    publishedAt: '2022-02-08T09:04:20.000Z',
  },
  {
    company: 'Moladin',
    departmentName: 'Technology',
    description: '',
    url: 'https://moladin.com/careers/14-Sr-Manager-of-Delivery-and-Excellence--(Technical-Program-Manager-&-Technical-Support)',
    jobTitle:
      'Sr Manager of Delivery and Excellence  (Technical Program Manager & Technical Support)',
    location: 'Remote',
    publishedAt: '2022-02-09T01:13:34.000Z',
  },
  {
    company: 'Moladin',
    departmentName: 'Technology',
    description: '',
    url: 'https://moladin.com/careers/15-Technical-Architect---Backend',
    jobTitle: 'Technical Architect - Backend',
    location: 'Remote',
    publishedAt: '2022-02-15T20:46:23.000Z',
  },
  {
    company: 'Moladin',
    departmentName: 'Technology',
    description: '',
    url: 'https://moladin.com/careers/16-Engineering-Manager-I',
    jobTitle: 'Engineering Manager I',
    location: 'Remote',
    publishedAt: '2022-02-19T21:04:22.000Z',
  },
  {
    company: 'Moladin',
    departmentName: 'Technology',
    description: '',
    url: 'https://moladin.com/careers/18-Software-Development-Engineer-in-Test',
    jobTitle: 'Software Development Engineer in Test',
    location: 'Remote',
    publishedAt: '2022-02-21T19:46:13.000Z',
  },
  {
    company: 'Moladin',
    departmentName: 'Technology',
    description: '',
    url: 'https://moladin.com/careers/20-Software-Development-Engineer-in-Test',
    jobTitle: 'Software Development Engineer in Test',
    location: 'Remote',
    publishedAt: '2022-02-21T19:46:13.000Z',
  },
  {
    company: 'Moladin',
    departmentName: 'Technology',
    description: '',
    url: 'https://moladin.com/careers/21-Technical-Program-Manager',
    jobTitle: 'Technical Program Manager',
    location: 'Remote',
    publishedAt: '2022-02-24T02:47:14.000Z',
  },
  {
    company: 'Moladin',
    departmentName: 'Technology',
    description: '',
    url: 'https://moladin.com/careers/22-Technical-Program-Manager',
    jobTitle: 'Technical Program Manager',
    location: 'Remote',
    publishedAt: '2022-02-24T02:47:14.000Z',
  },
  {
    company: 'Moladin',
    departmentName: 'Technology',
    description: '',
    url: 'https://moladin.com/careers/23-Software-Engineer---Backend-(Platform-Squad)',
    jobTitle: 'Software Engineer - Backend (Platform Squad)',
    location: 'Remote',
    publishedAt: '2022-02-25T07:37:09.000Z',
  },
  {
    company: 'Moladin',
    departmentName: 'Product',
    description: '',
    url: 'https://moladin.com/careers/25-Sr-Data-Analyst',
    jobTitle: 'Sr Data Analyst',
    location: 'Remote',
    publishedAt: '2022-03-08T02:46:20.000Z',
  },
  {
    company: 'Moladin',
    departmentName: 'Technology',
    description: '',
    url: 'https://moladin.com/careers/26-Senior-Software-Engineer---Android-(Freelance,-Kotlin)',
    jobTitle: 'Senior Software Engineer - Android (Freelance, Kotlin)',
    location: 'Remote',
    publishedAt: '2022-03-14T06:07:28.000Z',
  },
  {
    company: 'Moladin',
    departmentName: 'Technology',
    description: '',
    url: 'https://moladin.com/careers/27-Senior-Software-Engineer---Web-(Freelance,-ReactJS)',
    jobTitle: 'Senior Software Engineer - Web (Freelance, ReactJS)',
    location: 'Remote',
    publishedAt: '2022-03-14T06:15:18.000Z',
  },
  {
    company: 'Moladin',
    departmentName: 'Product',
    description: '',
    url: 'https://moladin.com/careers/28-UIUX-Designer',
    jobTitle: 'UIUX Designer',
    location: 'Remote',
    publishedAt: '2022-03-29T16:24:19.000Z',
  },
  {
    company: 'Moladin',
    departmentName: 'Product',
    description: '',
    url: 'https://moladin.com/careers/29-Associate-Senior-Product-Design',
    jobTitle: 'Associate Senior Product Design',
    location: 'Remote',
    publishedAt: '2022-03-29T17:03:16.000Z',
  },
  {
    company: 'Moladin',
    departmentName: 'Product',
    description: '',
    url: 'https://moladin.com/careers/30-Associate-Design-Lead',
    jobTitle: 'Associate Design Lead',
    location: 'Remote',
    publishedAt: '2022-03-29T19:48:23.000Z',
  },
  {
    company: 'Moladin',
    departmentName: 'Technology',
    description: '',
    url: 'https://moladin.com/careers/31-Sr.-Software-Engineer---Android-(-Refinancing-)',
    jobTitle: 'Sr. Software Engineer - Android ( Refinancing )',
    location: 'Remote',
    publishedAt: '2022-03-31T01:24:47.000Z',
  },
  {
    company: 'Moladin',
    departmentName: 'Technology',
    description: '',
    url: 'https://moladin.com/careers/53-Software-Engineer-Android',
    jobTitle: 'Software Engineer-Android',
    location: 'Remote',
    publishedAt: '2022-04-13T03:12:47.000Z',
  },
];
