import { JobOpening } from '../../../../lib/types';

export const Pinhome_JOBS: JobOpening[] = [
  {
    company: 'Pinhome',
    departmentName: 'Engineering',
    description: '',
    url: 'https://jobs.ashbyhq.com/Pinhome/a8052af8-aa37-48ae-adde-db12016ed1bd',
    jobTitle: 'AI Engineering Lead',
    location: 'Pinhome',
  },
  {
    company: 'Pinhome',
    departmentName: 'Engineering',
    description: '',
    url: 'https://jobs.ashbyhq.com/Pinhome/f5a0695b-8848-4167-b099-878fbba3ea13',
    jobTitle: 'Quality Assurance Engineer',
    location: 'Pinhome',
  },
  {
    company: 'Pinhome',
    departmentName: 'Engineering',
    description: '',
    url: 'https://jobs.ashbyhq.com/Pinhome/2bfc5e93-a864-47e8-ab32-22ae1cc002a0',
    jobTitle: 'Software Engineer',
    location: 'Pinhome',
  },
  {
    company: 'Pinhome',
    departmentName: 'Leadership',
    description: '',
    url: 'https://jobs.ashbyhq.com/Pinhome/4e8c28ec-071d-4ddd-86e7-d297622d166e',
    jobTitle: 'Head of Business Owner',
    location: 'Pinhome',
  },
  {
    company: 'Pinhome',
    departmentName: 'Leadership',
    description: '',
    url: 'https://jobs.ashbyhq.com/Pinhome/e6381583-b387-4125-8871-6d054de5950b',
    jobTitle: 'Head of Product ',
    location: 'Pinhome',
  },
  {
    company: 'Pinhome',
    departmentName: 'Leadership',
    description: '',
    url: 'https://jobs.ashbyhq.com/Pinhome/548b33d6-38db-47a5-8cbf-31a3b31b652f',
    jobTitle: 'Head of Product Design',
    location: 'Pinhome',
  },
  {
    company: 'Pinhome',
    departmentName: 'Marketing Communication and Public Relation',
    description: '',
    url: 'https://jobs.ashbyhq.com/Pinhome/748e8857-2137-46ad-a461-f1de70abcf71',
    jobTitle: 'Freelance Photographer (Bandung)',
    location: 'Bandung',
  },
  {
    company: 'Pinhome',
    departmentName: 'Operations',
    description: '',
    url: 'https://jobs.ashbyhq.com/Pinhome/18637d79-811b-4d06-ba73-9cb0b08e2399',
    jobTitle: 'Freelance Photo Editor',
    location: 'Pinhome',
  },
  {
    company: 'Pinhome',
    departmentName: 'Pinhome Capital',
    description: '',
    url: 'https://jobs.ashbyhq.com/Pinhome/2ecfde11-4aa4-4a06-82d8-88e4ae203596',
    jobTitle: 'Portfolio Manager',
    location: 'Pinhome',
  },
  {
    company: 'Pinhome',
    departmentName: 'Product',
    description: '',
    url: 'https://jobs.ashbyhq.com/Pinhome/876a04c9-8192-4701-9ac2-6387aa415599',
    jobTitle: 'Associate Product Designer (UI Focus)',
    location: 'Pinhome',
  },
  {
    company: 'Pinhome',
    departmentName: 'Product',
    description: '',
    url: 'https://jobs.ashbyhq.com/Pinhome/c9b804e3-4c79-479d-bc00-33bf4f6c90dc',
    jobTitle: 'Product Researcher',
    location: 'Pinhome',
  },
  {
    company: 'Pinhome',
    departmentName: 'Sales & Commercial',
    description: '',
    url: 'https://jobs.ashbyhq.com/Pinhome/5fb0e698-c65f-4a12-a2fa-1d77d1a62ee2',
    jobTitle: 'Commercial Ops and Performance Specialist',
    location: 'Pinhome',
  },
  {
    company: 'Pinhome',
    departmentName: 'Sales & Commercial',
    description: '',
    url: 'https://jobs.ashbyhq.com/Pinhome/7e75c8c0-fc1d-4c63-a093-899c09a15385',
    jobTitle: 'QA Officer Intern (On-Site/WFO)',
    location: 'Pinhome',
  },
  {
    company: 'Pinhome',
    departmentName: 'Subsidiary - Jagel',
    description: '',
    url: 'https://jobs.ashbyhq.com/Pinhome/15a586e1-015a-421f-9057-7b7272f60eca',
    jobTitle: 'Business Development & Strategy Associate',
    location: 'Jagel',
  },
  {
    company: 'Pinhome',
    departmentName: 'Subsidiary - Jagel',
    description: '',
    url: 'https://jobs.ashbyhq.com/Pinhome/7d94fa2b-ff4b-4352-9637-70be045cadde',
    jobTitle: 'Client Acquisition Specialist',
    location: 'Jagel',
  },
  {
    company: 'Pinhome',
    departmentName: 'Subsidiary - Jagel',
    description: '',
    url: 'https://jobs.ashbyhq.com/Pinhome/d827ad44-9b32-4b22-abd6-dea745c3edd2',
    jobTitle: 'Client Retention Specialist',
    location: 'Jagel',
  },
  {
    company: 'Pinhome',
    departmentName: 'Subsidiary - Jagel',
    description: '',
    url: 'https://jobs.ashbyhq.com/Pinhome/9061ca17-b974-4fcc-829f-318fa82c8db6',
    jobTitle: 'Digital Marketing Specialist',
    location: 'Jagel',
  },
  {
    company: 'Pinhome',
    departmentName: 'Subsidiary - Jagel',
    description: '',
    url: 'https://jobs.ashbyhq.com/Pinhome/6f7c0128-2ba4-4ef5-902b-2c1cb3c67664',
    jobTitle: 'Engineering Manager',
    location: 'Jagel',
  },
  {
    company: 'Pinhome',
    departmentName: 'Subsidiary - Jagel',
    description: '',
    url: 'https://jobs.ashbyhq.com/Pinhome/228345af-a3d3-47e8-a32e-7c7475f8f7b4',
    jobTitle: 'Full-Stack Engineer',
    location: 'Jagel',
  },
  {
    company: 'Pinhome',
    departmentName: 'Subsidiary - Jagel',
    description: '',
    url: 'https://jobs.ashbyhq.com/Pinhome/cfd6400d-cd86-4da6-a954-7fc301d35900',
    jobTitle: 'Legal Officer',
    location: 'Jagel',
  },
  {
    company: 'Pinhome',
    departmentName: 'Subsidiary - Jagel',
    description: '',
    url: 'https://jobs.ashbyhq.com/Pinhome/31ec9ff7-a567-4d47-a58b-9e83f5766286',
    jobTitle: 'Marketing Supervisor',
    location: 'Jagel',
  },
  {
    company: 'Pinhome',
    departmentName: 'Subsidiary - Jagel',
    description: '',
    url: 'https://jobs.ashbyhq.com/Pinhome/98c28c43-2eda-4b62-8791-f24f5d24530c',
    jobTitle: 'Partnership & Event Specialist',
    location: 'Jagel',
  },
  {
    company: 'Pinhome',
    departmentName: 'Subsidiary - Jagel',
    description: '',
    url: 'https://jobs.ashbyhq.com/Pinhome/854a4c88-4cd7-4861-a855-a5d5ae46ac93',
    jobTitle: 'Product Designer',
    location: 'Jagel',
  },
  {
    company: 'Pinhome',
    departmentName: 'Subsidiary - Jagel',
    description: '',
    url: 'https://jobs.ashbyhq.com/Pinhome/421d7440-dec4-4e7b-bb79-6c40de461cd8',
    jobTitle: 'Product Manager - Lead',
    location: 'Jagel',
  },
  {
    company: 'Pinhome',
    departmentName: 'Subsidiary - Jagel',
    description: '',
    url: 'https://jobs.ashbyhq.com/Pinhome/f1975927-42f3-49fa-a084-4ef9b046366b',
    jobTitle: 'Quality Assurance Analyst',
    location: 'Jagel',
  },
  {
    company: 'Pinhome',
    departmentName: 'Subsidiary - Jagel',
    description: '',
    url: 'https://jobs.ashbyhq.com/Pinhome/7531ffbb-c110-4cfe-a838-7103c142dbbd',
    jobTitle: 'Senior Product Designer ',
    location: 'Jagel',
  },
  {
    company: 'Pinhome',
    departmentName: 'Subsidiary - Jagel',
    description: '',
    url: 'https://jobs.ashbyhq.com/Pinhome/b91939a1-3e03-4020-9e7f-f67f88af6ddd',
    jobTitle: 'Tax Officer',
    location: 'Jagel',
  },
  {
    company: 'Pinhome',
    departmentName: 'Subsidiary - Jagel',
    description: '',
    url: 'https://jobs.ashbyhq.com/Pinhome/a1d1a36e-bcad-45c1-8b33-866ba126dc3c',
    jobTitle: 'Technical Support',
    location: 'Jagel',
  },
];
