import { scrape as Pinhome } from './Pinhome';
import { scrape as eFishery } from './eFishery';
import { scrape as Pahamify } from './Pahamify';
import { scrape as CoLearn } from './CoLearn';
import { scrape as QasirId } from './QasirId';
import { scrape as Finantier } from './Finantier';
import { scrape as ALAMI } from './ALAMI';
import { scrape as BukuWarung } from './BukuWarung';
import { scrape as FlipId } from './FlipId';
import { scrape as Moladin } from './Moladin';
import { scrape as HappyFresh } from './HappyFresh';
import { scrape as Ajaib } from './Ajaib';
import { scrape as KataAi } from './KataAi';
import { scrape as StockbitBibit } from './StockbitBibit';

Pinhome();
eFishery();
Pahamify();
CoLearn();
QasirId();
Finantier();
ALAMI();
BukuWarung();
FlipId();
Moladin();
HappyFresh();
Ajaib();
KataAi();
StockbitBibit();
